//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieComment
    {
        public int Id { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> CommentID { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Movy Movy { get; set; }
    }
}
