//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movy()
        {
            this.MovieGenres = new HashSet<MovieGenre>();
        }
    
        public int Id { get; set; }
        public string Image { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public string Production { get; set; }
        public string Duration { get; set; }
        public string Director { get; set; }
        public string ActorID { get; set; }
        public Nullable<double> Imdb { get; set; }
        public string Video { get; set; }
        public string Slider { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieGenre> MovieGenres { get; set; }
    }
}
