//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movy()
        {
            this.Comments = new HashSet<Comment>();
            this.MovieActors = new HashSet<MovieActor>();
            this.MovieGenres = new HashSet<MovieGenre>();
            this.MovieSeans = new HashSet<MovieSean>();
            this.SeansTables = new HashSet<SeansTable>();
        }
    
        public int Id { get; set; }
        public string Image { get; set; }
        public Nullable<int> Number { get; set; }
        public string Name { get; set; }
        public string Production { get; set; }
        public string Duration { get; set; }
        public Nullable<double> Year { get; set; }
        public string Director { get; set; }
        public Nullable<double> Imdb { get; set; }
        public string Video { get; set; }
        public Nullable<bool> Slider { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Info { get; set; }
        public Nullable<bool> Top { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieActor> MovieActors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieGenre> MovieGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieSean> MovieSeans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeansTable> SeansTables { get; set; }
    }
}
